
# Overview 

Let's compute the Median Length of Words in random text like [here](http://generator.lorem-ipsum.info/) using numpy 



In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:

# Dataset 

data = """
Lorem ipsum is a pseudo-Latin text used in web design, typography, layout, and printing in place of English to emphasise design elements over content. It's also called placeholder (or filler) text. It's a convenient tool for mock-ups. It helps to outline the visual elements of a document or presentation, eg typography, font, or layout. Lorem ipsum is mostly a part of a Latin text by the classical author and philosopher Cicero. Its words and letters have been changed by addition or removal, so to deliberately render its content nonsensical; it's not genuine, correct, or comprehensible Latin anymore. While lorem ipsum's still resembles classical Latin, it actually has no meaning whatsoever. As Cicero's text doesn't contain the letters K, W, or Z, alien to latin, these, and others are often inserted randomly to mimic the typographic appearence of European languages, as are digraphs not to be found in the original.
"""



In [0]:

words = data.split()


In [3]:
words

['Lorem',
 'ipsum',
 'is',
 'a',
 'pseudo-Latin',
 'text',
 'used',
 'in',
 'web',
 'design,',
 'typography,',
 'layout,',
 'and',
 'printing',
 'in',
 'place',
 'of',
 'English',
 'to',
 'emphasise',
 'design',
 'elements',
 'over',
 'content.',
 "It's",
 'also',
 'called',
 'placeholder',
 '(or',
 'filler)',
 'text.',
 "It's",
 'a',
 'convenient',
 'tool',
 'for',
 'mock-ups.',
 'It',
 'helps',
 'to',
 'outline',
 'the',
 'visual',
 'elements',
 'of',
 'a',
 'document',
 'or',
 'presentation,',
 'eg',
 'typography,',
 'font,',
 'or',
 'layout.',
 'Lorem',
 'ipsum',
 'is',
 'mostly',
 'a',
 'part',
 'of',
 'a',
 'Latin',
 'text',
 'by',
 'the',
 'classical',
 'author',
 'and',
 'philosopher',
 'Cicero.',
 'Its',
 'words',
 'and',
 'letters',
 'have',
 'been',
 'changed',
 'by',
 'addition',
 'or',
 'removal,',
 'so',
 'to',
 'deliberately',
 'render',
 'its',
 'content',
 'nonsensical;',
 "it's",
 'not',
 'genuine,',
 'correct,',
 'or',
 'comprehensible',
 'Latin',
 'anymore.',
 'Whil

In [0]:
# NOTE: Build a Function to be applied to the vector of words 
mylen = np.vectorize(len)


In [0]:
# NOTE: Build the vector of words length
words_length = mylen(words)


In [8]:
words_length

array([ 5,  5,  2,  1, 12,  4,  4,  2,  3,  7, 11,  7,  3,  8,  2,  5,  2,
        7,  2,  9,  6,  8,  4,  8,  4,  4,  6, 11,  3,  7,  5,  4,  1, 10,
        4,  3,  9,  2,  5,  2,  7,  3,  6,  8,  2,  1,  8,  2, 13,  2, 11,
        5,  2,  7,  5,  5,  2,  6,  1,  4,  2,  1,  5,  4,  2,  3,  9,  6,
        3, 11,  7,  3,  5,  3,  7,  4,  4,  7,  2,  8,  2,  8,  2,  2, 12,
        6,  3,  7, 12,  4,  3,  8,  8,  2, 14,  5,  8,  5,  5,  7,  5,  9,
        9,  6,  2,  8,  3,  2,  7, 11,  2,  8,  4,  7,  7,  3,  7,  2,  2,
        2,  2,  5,  2,  6,  6,  3,  6,  3,  5,  8,  8,  2,  5,  3, 11, 10,
        2,  8, 10,  2,  3,  8,  3,  2,  2,  5,  2,  3,  9])

In [9]:
# NOTE: Plot the words length Histogram 
plt.hist(words_length)


(array([38., 19., 13., 28., 15., 16.,  9.,  6.,  3.,  2.]),
 array([ 1. ,  2.3,  3.6,  4.9,  6.2,  7.5,  8.8, 10.1, 11.4, 12.7, 14. ]),
 <a list of 10 Patch objects>)

In [11]:
# NOTE: Compute the median 
np.median(words_length)

5.0